version: "3.7"

services:
  db:
    image: postgres
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5435:5432"